const controller = require("../controllers/admin.controller");
const key_words_controller = require("../controllers/admin/key_word");
const authAdmin = require("../middleware/auth.admin");
const express = require("express");
const router = express.Router();
router.delete("/keyword/checkAndDelete", controller.adminCheckAndDelteBig5EnvIndicator);
router.get("/keywords/getAll", key_words_controller.getAll);
router.get("/questions/getByBig5EnvIndicator", controller.adminGetQuestionsByBig5EnvIndcator);
router.get("/numbertrait", controller.getTraitNumberUser);
router.get("/user", controller.adminUserHome);
router.get("/question", controller.adminQuestionHome);
router.get("/getquestions", controller.adminGetQuestions);
router.get("/getQuestionsBig5EnvInicator", controller.adminGetQuestionsByIndicator);
router.post("/sendquestion", controller.adminSendQuestion);
router.post("/addquestion", controller.adminAddQuestionPost);
router.post("/addBig5EnvIndicator", controller.adminAddBig5EnvIndicatorPost);
router.delete("/deleteAllBig5EnvIndicator", controller.adminDeleteAllBig5EnvIndicator);
router.post("/adminCheckIndicator", controller.adminCheckIndicator);
router.get("/getBig5EnvIndicator", controller.adminGetIndicator);
router.get("/getAddress", controller.adminGetAddress);
router.get("/getusers", controller.adminGetUsers);
router.get("/logout", controller.adminLogout);
router.get("/", controller.adminHome);
module.exports = router;